[pytest]

#для отображения всех результатов в консоли (softassert-ы)
addopts =
;    --check-max-tb=100
    --alluredir=allure-results

markers =
    smoke: smoke tests
    regress: regress tests
    no_headless
    ui: UI tests